version: "3.9"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent node_modules overwrite
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000/api
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

  celery:
    build: ./backend
    command: celery -A ecommerce worker -l info
    volumes:
      - ./backend:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  pgdata:
